name: celloffun_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  uuid: ^4.3.3
  web_socket_channel: ^2.4.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
